import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('JAhxAgvAwTbAgyAukBwTzBiuAgnAhJAEAg3BRAh2BsUAidAp-AhpChGBicBBAAAgoBtTBADjZEg9Bt_GACEAABSAgtAADACwyZCBAhvAicHAAAAPDBB3bLBkMAAAjiEnVBhdBiWCiSCmKA1UTCqbAgvAwSFAjGAkvHjgGwUGBh0DxOtD');
