import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('grAPCg8AAAgsADAgkAeAr9AoOCxo6AMAgmCMCiKAgmEFAhDEEBDABABAGAeBBAAAekLHDTBhZAdYgnFnUAIAg1HhuAlPEBDAAAXJPj_iCVg-DfBkBgvUBF4M_bAs3AACijAPCg8AAAiCAFD4NbTAYAeAYAeAYAeAYAeAYA');
